### ISSUE TITLE
Use content:// Uri for a file instead of a file:/// Uri

### ISSUE THREAD

**Issue by drstranges** [ekimual/croperino#1]
"Passing file:// URIs outside the package domain may leave the receiver with an unaccessible path. Therefore, attempts to pass a file:// URI trigger a FileUriExposedException (Android N). The recommended way to share the content of a private file is using the FileProvider."

**Comment by ekimual** [comment]
@drstranges Sorry for the very late reply, I currently don't have Android 6 + devices I will update this once I get one.

**Comment by ekimual** [comment]
@drstranges Fixed with 1.0.3
