### ISSUE TITLE
How to set cropview to be fix as square, it should not be zoom in or zoom out rather it should be fixed size.

### ISSUE THREAD

**Issue by iamnitesh** [ekimual/croperino#11]
I have implemented your Project in that CropImageView I have comment out ZoomIn and ZoomOut method  but nothing has changed .

```
  @Override
    protected void zoomIn() {

        super.zoomIn();
        for (HighlightView hv : mHighlightViews) {
            hv.mMatrix.set(getImageMatrix());
            hv.invalidate();
        }
    }

    @Override
    protected void zoomOut() {

        super.zoomOut();
        for (HighlightView hv : mHighlightViews) {
            hv.mMatrix.set(getImageMatrix());
            hv.invalidate();
        }
    }
```
hope you suggest me way to find my solution.

**Comment by RelocationTime** [comment]
private void centerBasedOnHighLightView(HighLightView hv)	 {
		Rect drawRect = hv.mDrawRect;
		float width = drawRect.width();
		float height = drawRect.height();

		float thisWidth = getWidth();
		float thisHeight = getHeight();

		float z1 = thisWidth / width * .6F;
		float z2 = thisHeight / height * .6F;
		float zoom = Math.min(z1, z2);
		zoom = zoom * this.getScale();
		zoom = Math.max(1F, zoom);

		if ((Math.abs(zoom - getScale()) / zoom) > .1) {
			if (hv.mCropRect.left <= this.getLeft() || hv.mCropRect.top <= this.getTop() || hv.mCropRect.right >= this.getRight() || hv.mCropRect.bottom >= this.getBottom()) {
				return;
			}

			float[] coordinates = new float[]{hv.mCropRect.centerX(),
					hv.mCropRect.centerY()};
			getImageMatrix().mapPoints(coordinates);
			zoomTo(zoom, coordinates[0], coordinates[1], 300F);
		}

		ensureVisible(hv);
	}

这个方法，在对cropRect进行zoom的时候，会超出屏幕，都到屏幕外面去了，怎么做

**Comment by ekimual** [comment]
Cropping is fixed as Square when you set the aspect X and aspect Y as 1. For zooming option feel free to play around with the zoomIn, zoomTo, zoomOut functions and modify it to fit your needs.
