### ISSUE TITLE
updating original image

### ISSUE THREAD

**Issue by sarang1996** [ekimual/croperino#13]
it's a nice plugin for cropping but I don't want to store image and also don't want to update original one, just want to store the image in temp file so it cannot be affected to original image. @ekimual

**Comment by ekimual** [comment]
@sarang1996 that is the main purpose of the library however you can do a File delete if ever you do not want to store it. You can do something like, Snap > Crop > Upload to server then clean the Directory you pointed to make sure it is not stored.

**Comment by sarang1996** [comment]
however, I couldn't find how to create a temp file and I can't fix my frame also. an image is still zoom in and out. @ekimual
