### ISSUE TITLE
when choosing the picture from gallery and crop issue..!

### ISSUE THREAD

**Issue by MikeB32** [ekimual/croperino#15]
when i choose the picture from the gallery and crop it 
it saving on the same picture so ruining the original image

**Comment by ekimual** [comment]
Any details?

**Comment by MikeB32** [comment]
when u crop a picture it overrides the orginal picture : it deletes the
orginal one and replace it with the crop one

**Comment by ekimual** [comment]
@MikeB32 Fixed in v1.1.2 :)

**Comment by MikeB32** [comment]
Donee.!
thx dude,,!
