### ISSUE TITLE
Image is not saved.

### ISSUE THREAD

**Issue by sarang1996** [ekimual/croperino#21]
I have used the code as you say but it is not saving cropped images in any directory either in my custom folder or DCIM (inbuilt). help! @ekimual

**Comment by ekimual** [comment]
@sarang1996 have you updated to v1.1.2? Can I see some source code / logs and device information..

**Comment by sarang1996** [comment]
I have solved it just I am using as your documentation but when we are initializing a folder there is one '/' needed in last. please updated. @ekimual
