### ISSUE TITLE
I want to add a circle inside the rectangle.

### ISSUE THREAD

**Issue by pixelpointtechnology** [ekimual/croperino#22]
Currently highlightedview has only square but I want to add circle inside the sqaure in highlightedview.

**Comment by ekimual** [comment]
You might want to fork the library and modify it to fit your needs, sorry as I think this request is out of scope for the library and is actually a request and not an issue. I found an alternative that you might be interested in [https://github.com/adamstyrc/cookie-cutter](https://github.com/adamstyrc/cookie-cutter)
