### ISSUE TITLE
dont start CropImage activity when use this library within fragment

### ISSUE THREAD

**Issue by tmediaa** [ekimual/croperino#27]
in fragment onCreateView add this code:
`new CroperinoConfig("IMG_" + System.currentTimeMillis() + ".jpg", "/MikeLau/Pictures", "/sdcard/MikeLau/Pictures");
        CroperinoFileUtil.verifyStoragePermissions(getActivity());
        CroperinoFileUtil.setupDirectory(getContext());`
and add this code in fragment class: 

`private void openImagePickerIntent() {
        if (CroperinoFileUtil.verifyStoragePermissions(getActivity())) {
            prepareChooser();
        }else{

        }
    }
    private void prepareChooser() {
        Croperino.prepareChooser(getActivity(), "انتخاب تصویر از ...", ContextCompat.getColor(getContext(), android.R.color.background_dark));
    }
    private void prepareCamera() {
        Croperino.prepareCamera(getActivity());
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        Log.d(CONST.APP_LOG,"onActit result");
        switch (requestCode) {
            case CroperinoConfig.REQUEST_TAKE_PHOTO:
                if (resultCode == Activity.RESULT_OK) {
                    Croperino.runCropImage(CroperinoFileUtil.getmFileTemp(), getActivity(), true, 16, 9, 0, 0);
                }
                break;
            case CroperinoConfig.REQUEST_PICK_FILE:
                if (resultCode == Activity.RESULT_OK) {
                    CroperinoFileUtil.newGalleryFile(data, getActivity());
                    Croperino.runCropImage(CroperinoFileUtil.getmFileTemp(), getActivity(), true, 16, 9, 0, 0);
                }
                break;
            case CroperinoConfig.REQUEST_CROP_PHOTO:
                if (resultCode == Activity.RESULT_OK) {
                    Uri i = Uri.fromFile(CroperinoFileUtil.getmFileTemp());
                    //ivMain.setImageURI(i);
                    Log.d(CONST.APP_LOG,"url: " + i.getPath());
                }
                break;
            default:
                break;
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);

        if (requestCode == CroperinoFileUtil.REQUEST_CAMERA) {
            for (int i = 0; i < permissions.length; i++) {
                String permission = permissions[i];
                int grantResult = grantResults[i];

                if (permission.equals(Manifest.permission.CAMERA)) {
                    if (grantResult == PackageManager.PERMISSION_GRANTED) {
                        prepareCamera();
                    }
                }
            }
        } else if (requestCode == CroperinoFileUtil.REQUEST_EXTERNAL_STORAGE) {
            boolean wasReadGranted = false;
            boolean wasWriteGranted = false;

            for (int i = 0; i < permissions.length; i++) {
                String permission = permissions[i];
                int grantResult = grantResults[i];

                if (permission.equals(Manifest.permission.READ_EXTERNAL_STORAGE)) {
                    if (grantResult == PackageManager.PERMISSION_GRANTED) {
                        wasReadGranted = true;
                    }
                }
                if (permission.equals(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
                    if (grantResult == PackageManager.PERMISSION_GRANTED) {
                        wasWriteGranted = true;
                    }
                }
            }

            if (wasReadGranted && wasWriteGranted) {
                prepareChooser();
            }
        }
    }`
when start activity and select file from gallery or camera "CropImage " activity don't open and nothing happend
how to solve this problem ?

**Comment by ekimual** [comment]
@tmediaa can you try this in version 1.1.7 also I'm not sure if you are handling the activity / fragment life cycle correctly.
