### ISSUE TITLE
Is it safe to remove <uses-feature android:name="android.hardware.camera.autofocus" />?

### ISSUE THREAD

**Issue by ferrytan** [ekimual/croperino#30]
Hello, I've been using Croperino for my app.
it's been the best and fits my requirement the most for choosing pictures and crop them.

But since i use this feature line in manifest, some of my users with low end devices which have no autofocus feature, cannot download this app. playstore said the device is incompatible.
`<uses-feature android:name="android.hardware.camera.autofocus" />`

I've tested removing this line in manifest, the app runs well and can use the camera nicely,
but is it really safe to remove this feature and keep using this library?

**Comment by ekimual** [comment]
So far I did remove it as well in some of my devices that doesn't support it, and it works fine. Closing the issue, file another one if anything comes up.
