### ISSUE TITLE
How to change the aspect ratio ?

### ISSUE THREAD

**Issue by coutlooters** [ekimual/croperino#6]
@ekimual 
The image derived from the camera, goes to the crop screen.
but the aspect ratio of the cropper is always square, how do i keep it free size ?

**Comment by ekimual** [comment]
@coutlooters make the first 2 integers 0 to ignore aspect ratio, it will be square at first but you can adjust it.

`Croperino.runCropImage(CroperinoFileUtil.getmFileTemp(), MainActivity.this, true, 0, 0, 0, 0);`

**Comment by coutlooters** [comment]
@ekimual I  m very much impressed with the library, plus the immediate response given for the Issue which is solved by making the changes mentioned.

Thank you very much.

**Comment by ekimual** [comment]
@coutlooters Very much appreciated and I will try to have this updated once I have a new device (Android 6+ ) and free time to do. :)
